import type {Metadata} from "next";
import Image from "next/image";
import {Handshake,Network,ShieldCheck,Truck} from "lucide-react";
import {Navbar} from "@/components/layout/Navbar";
import {Footer} from "@/components/layout/Footer";
import {Container} from "@/components/ui/Container";
import {ContactForm} from "@/components/forms/ContactForm";
export const metadata:Metadata={title:"Vendor & Business Partnership",description:"GEGA partnership for suppliers, vendors, subcontractors, specialist providers, logistics partners and business partners.",alternates:{canonical:"https://gcnusantara.com/partnership"}};
const types=[
 [Handshake,"Supplier / Vendor","Produk, material, equipment, atau capability supply yang relevan dengan kebutuhan customer."],
 [ShieldCheck,"Specialist Provider","Kemampuan teknis atau layanan spesialis yang dapat mendukung kebutuhan proyek."],
 [Truck,"Logistics Partner","Dukungan logistik dan delivery sesuai kebutuhan transaksi atau proyek."],
 [Network,"Business / Project Partner","Kolaborasi berbasis opportunity atau project dengan scope, tanggung jawab, dan commercial arrangement yang terdokumentasi."],
];
export default function Page(){return <main><Navbar/><section className="relative min-h-[560px] overflow-hidden bg-[#041827] pt-[72px] text-white md:pt-20"><Image src="/assets/generated/project-machinery-001.jpg" alt="Representational supplier and industrial partnership environment" fill priority sizes="100vw" className="object-cover opacity-[.25]"/><div className="absolute inset-0 bg-gradient-to-r from-[#041827] via-[#041827]/94 to-[#041827]/55"/><Container className="relative flex min-h-[488px] items-end pb-16 pt-24"><div className="max-w-3xl"><div className="text-[11px] font-semibold uppercase tracking-[.17em] text-cyan">Partnership Ecosystem</div><h1 className="mt-5 text-5xl font-semibold tracking-[-.045em] text-white md:text-7xl">Tumbuh melalui jaringan yang tepat.</h1><p className="mt-6 max-w-2xl text-[17px] leading-8 text-white/68">GEGA membangun jaringan supplier, vendor, subcontractor, specialist provider, logistics partner, dan business partner untuk memenuhi kebutuhan customer secara lebih efektif dan bertanggung jawab.</p></div></Container></section><section className="bg-white py-20 md:py-24"><Container><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{types.map(([Icon,title,desc])=>{const C=Icon as typeof Handshake;return <div key={String(title)} className="rounded-2xl border border-navy/10 bg-[#f8fafb] p-7"><C size={24} className="text-corporate"/><h2 className="mt-5 text-lg font-semibold text-navy">{String(title)}</h2><p className="mt-3 text-sm leading-6 text-navy/62">{String(desc)}</p></div>})}</div><div className="mt-12 rounded-2xl border border-cyan/20 bg-cyan/[.05] p-6 text-sm leading-7 text-navy/65"><strong className="text-navy">Prinsip kemitraan:</strong> pengajuan informasi perusahaan tidak berarti vendor approval otomatis. Kesesuaian scope, dokumentasi, kualitas, kapasitas, commercial terms, risiko, dan kebutuhan project tetap direview sesuai konteks.</div></Container></section><section className="bg-[#f4f8fa] py-20 md:py-24"><Container className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><div className="section-kicker">Menjadi Vendor / Partner</div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl">Perkenalkan perusahaan dan kapabilitas Anda.</h2><p className="mt-5 text-[15px] leading-7 text-navy/62">Gunakan form ini untuk memperkenalkan perusahaan, scope, kategori produk/layanan, wilayah coverage, dan informasi relevan lain. Tim GEGA akan meninjau berdasarkan kebutuhan bisnis atau project yang tersedia.</p><div className="mt-8 text-sm leading-7 text-navy/65"><div>Kawasan Pergudangan dan Industri PKT Bitung, Blok A6–A7</div><div>Tangerang, Banten</div><a className="mt-3 block font-medium text-corporate" href="mailto:sales@gcnusantara.com">sales@gcnusantara.com</a></div></div><div className="rounded-2xl border border-navy/10 bg-white p-6 md:p-8"><ContactForm/></div></Container></section><Footer/></main>}
