import Image from "next/image";
import Link from "next/link";
import {Container} from "@/components/ui/Container";
import {T} from "@/components/i18n/T";

const CAPABILITIES=[
 {href:"/aviation-supply",en:"Aviation Supply",id:"Aviation Supply"},
 {href:"/procurement-sourcing",en:"Procurement & Sourcing",id:"Procurement & Sourcing"},
 {href:"/general-supply-trading",en:"General Supply & Trading",id:"General Supply & Trading"},
 {href:"/industrial-supply",en:"Industrial Supply",id:"Industrial Supply"},
 {href:"/project-based-supply",en:"Project-Based Supply",id:"Project-Based Supply"},
 {href:"/construction",en:"Construction",id:"Konstruksi"},
];
export function Footer(){return <footer className="bg-[#041827] text-white pt-16 md:pt-20 pb-8"><Container><div className="grid gap-12 border-b border-white/10 pb-14 md:grid-cols-[1.25fr_.8fr_1fr_1fr]"><div className="max-w-sm"><div className="flex items-center gap-3"><Image src="/gcn-logo.svg" alt="GCN" width={58} height={58} className="h-14 w-14"/><div><div className="text-sm font-bold tracking-[.04em]">PT GEGA CAHAYA NUSANTARA</div><div className="mt-1 text-[10px] uppercase tracking-[.15em] text-cyan">Your Trusted Business Partner</div></div></div><p className="mt-5 text-[14px] leading-7 text-white/60"><T en="B2B procurement, sourcing, supply and project execution connecting business requirements with the right capabilities and partners." id="Procurement, sourcing, supply, dan eksekusi proyek B2B yang menghubungkan kebutuhan bisnis dengan kapabilitas dan mitra yang tepat."/></p></div><div className="flex flex-col gap-3"><span className="mb-1 text-[11px] font-semibold uppercase tracking-[.15em] text-cyan"><T en="Company" id="Perusahaan"/></span><Link href="/company" className="text-sm text-white/65 hover:text-white"><T en="About GEGA" id="Tentang GEGA"/></Link><Link href="/company#vision" className="text-sm text-white/65 hover:text-white"><T en="Vision & Mission" id="Visi & Misi"/></Link><Link href="/company#sinergi" className="text-sm text-white/65 hover:text-white">SINERGI</Link><Link href="/partnership" className="text-sm text-white/65 hover:text-white"><T en="Partnership" id="Kemitraan"/></Link></div><div className="flex flex-col gap-3"><span className="mb-1 text-[11px] font-semibold uppercase tracking-[.15em] text-cyan"><T en="Capabilities" id="Kapabilitas"/></span>{CAPABILITIES.map(x=><Link key={x.href} href={x.href} className="text-sm text-white/65 hover:text-white"><T en={x.en} id={x.id}/></Link>)}</div><div className="flex flex-col gap-3"><span className="mb-1 text-[11px] font-semibold uppercase tracking-[.15em] text-cyan"><T en="Contact" id="Kontak"/></span><p className="text-sm leading-6 text-white/65">Kawasan Pergudangan dan Industri PKT Bitung<br/>Blok A6–A7, Tangerang, Banten</p><a href="mailto:sales@gcnusantara.com" className="text-sm text-white/65 hover:text-white">sales@gcnusantara.com</a><Link href="/rfq" className="mt-2 w-fit rounded-md border border-cyan/50 px-4 py-2.5 text-xs font-semibold text-cyan hover:bg-cyan hover:text-[#041827]"><T en="Submit RFQ" id="Ajukan RFQ"/></Link></div></div><div className="flex flex-col gap-4 pt-7 text-[11px] text-white/40 md:flex-row md:items-center md:justify-between"><span>© 2026 PT Gega Cahaya Nusantara.</span><div className="flex flex-wrap gap-5"><Link href="/privacy-policy" className="hover:text-white"><T en="Privacy Policy" id="Kebijakan Privasi"/></Link><Link href="/rfq" className="hover:text-white"><T en="RFQ / Contact" id="RFQ / Kontak"/></Link></div></div></Container></footer>}
