import Link from "next/link";import {Container} from "@/components/ui/Container";import {T} from "@/components/i18n/T";
const NAV=[
 {en:"Home",id:"Beranda",href:""},
 {en:"About",id:"Tentang Kami",href:"about"},
 {en:"Projects",id:"Proyek",href:"projects"},
 {en:"Contact",id:"Kontak",href:"contact"},
];
const LEGAL=[
 {en:"NIB (Business ID Number)",id:"NIB (Nomor Induk Berusaha)",value:"[ISI NIB]"},
 {en:"NPWP",id:"NPWP",value:"[ISI NPWP]"},
 {en:"Deed of Establishment",id:"Akta Pendirian",value:"[ISI DATA AKTA]"},
 {en:"Ministry of Law Decree (SK)",id:"SK Kemenkumham",value:"[ISI DATA SK]"},
];
export function Footer(){return <footer className="bg-deep-blue text-white pt-20 pb-10"><Container><div className="grid md:grid-cols-4 gap-12 pb-16 border-b border-white/10"><div><span className="text-h3 text-lg">PT GEGA CAHAYA NUSANTARA</span><p className="text-white/60 text-[15px] mt-4"><T en="Supply, Trading &amp; Construction" id="Supply, Trading &amp; Konstruksi"/></p><p className="text-white/40 text-caption mt-2"><T en="Established 2015" id="Berdiri sejak 2015"/></p></div><div className="flex flex-col gap-3"><span className="text-caption uppercase tracking-widest text-electric mb-2"><T en="Navigation" id="Navigasi"/></span>{NAV.map(l=><Link key={l.href} href={`/${l.href}`} className="text-white/70 hover:text-white text-[15px] w-fit"><T en={l.en} id={l.id}/></Link>)}</div><div className="flex flex-col gap-3"><span className="text-caption uppercase tracking-widest text-electric mb-2"><T en="Core Business" id="Bidang Usaha"/></span>{[{en:"Supply",id:"Supply"},{en:"Trading",id:"Trading"},{en:"Construction",id:"Construction"}].map(x=><span key={x.en} className="text-white/70 text-[15px]"><T en={x.en} id={x.id}/></span>)}</div><div className="flex flex-col gap-3"><span className="text-caption uppercase tracking-widest text-electric mb-2"><T en="Contact" id="Kontak"/></span><p className="text-white/70 text-[15px] leading-relaxed">Kawasan Pergudangan dan Industri PKT Bitung<br/>Blok A6–A7, Tangerang, Banten</p><a href="mailto:sales@gcnusantara.com" className="text-white/70 hover:text-white text-[15px]">sales@gcnusantara.com</a><Link href="/rfq" className="text-white hover:text-electric text-[15px]"><T en="Submit a requirement →" id="Ajukan kebutuhan Anda →"/></Link></div></div><div className="py-10 border-b border-white/10"><span className="text-caption uppercase tracking-widest text-electric mb-4 block"><T en="Legal & Registration" id="Legalitas Perusahaan"/></span><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-x-8 gap-y-3">{LEGAL.map(l=><div key={l.en} className="flex items-baseline justify-between gap-4 text-[13px] border-b border-white/10 pb-2"><span className="text-white/50"><T en={l.en} id={l.id}/></span><span className="text-white/70 font-medium whitespace-nowrap">{l.value}</span></div>)}</div></div><div className="flex flex-col md:flex-row items-center justify-between gap-4 pt-8 text-white/40 text-caption"><span><T en="© 2026 PT Gega Cahaya Nusantara. All rights reserved." id="© 2026 PT Gega Cahaya Nusantara. Hak cipta dilindungi."/></span><div className="flex gap-6"><Link href="/contact" className="hover:text-white"><T en="Contact" id="Kontak"/></Link><Link href="/rfq" className="hover:text-white"><T en="Request a Quotation" id="Ajukan Penawaran"/></Link><Link href="/privacy-policy" className="hover:text-white"><T en="Privacy Policy" id="Kebijakan Privasi"/></Link></div></div></Container></footer>}
