import { Container } from "@/components/ui/Container";
import { SectionHeader } from "@/components/ui/SectionHeader";
import { T } from "@/components/i18n/T";
const STEPS=[
  {n:"01",titleEn:"Understand",titleId:"Memahami",bodyEn:"Clarify scope, specification, quantity, site conditions, and delivery requirements.",bodyId:"Memperjelas ruang lingkup, spesifikasi, kuantitas, kondisi lokasi, dan kebutuhan pengiriman."},
  {n:"02",titleEn:"Plan",titleId:"Merencanakan",bodyEn:"Break the requirement into work packages, materials, suppliers, and execution needs.",bodyId:"Memecah kebutuhan menjadi paket pekerjaan, material, supplier, dan kebutuhan pelaksanaan."},
  {n:"03",titleEn:"Source",titleId:"Mencari Sumber",bodyEn:"Identify suitable products, suppliers, contractors, and commercial options.",bodyId:"Mengidentifikasi produk, supplier, kontraktor, dan opsi komersial yang sesuai."},
  {n:"04",titleEn:"Coordinate",titleId:"Mengoordinasikan",bodyEn:"Align procurement, site activities, logistics, documentation, and stakeholders.",bodyId:"Menyelaraskan pengadaan, kegiatan lokasi, logistik, dokumentasi, dan pemangku kepentingan."},
  {n:"05",titleEn:"Close",titleId:"Menyelesaikan",bodyEn:"Support delivery, inspection, handover, and completion documentation.",bodyId:"Mendukung pengiriman, inspeksi, serah terima, dan dokumentasi penyelesaian."},
];
export function HowWeWork(){return <section className="py-24 md:py-32 bg-white"><Container><SectionHeader eyebrow={<T en="Our Process" id="Proses Kami"/>} title={<T en="A disciplined path from requirement to delivery" id="Alur yang disiplin dari kebutuhan hingga pengiriman"/>} align="center"/><div className="hidden md:grid grid-cols-5 gap-6 mt-16 relative"><div className="absolute top-[13px] left-0 right-0 h-px bg-mist"/>{STEPS.map(s=><div key={s.n} className="relative flex flex-col gap-4"><div className="w-7 h-7 rounded-full bg-deep-blue text-white text-[12px] flex items-center justify-center relative z-10">{s.n.slice(1)}</div><h3 className="text-h3 text-lg"><T en={s.titleEn} id={s.titleId}/></h3><p className="text-[15px] text-navy/70 leading-relaxed"><T en={s.bodyEn} id={s.bodyId}/></p></div>)}</div><div className="md:hidden flex flex-col mt-12 relative pl-8"><div className="absolute top-2 bottom-2 left-[13px] w-px bg-mist"/>{STEPS.map(s=><div key={s.n} className="relative pb-10 last:pb-0"><div className="absolute -left-8 top-0 w-7 h-7 rounded-full bg-deep-blue text-white text-[12px] flex items-center justify-center">{s.n.slice(1)}</div><h3 className="text-h3 text-lg"><T en={s.titleEn} id={s.titleId}/></h3><p className="text-[15px] text-navy/70 leading-relaxed mt-2"><T en={s.bodyEn} id={s.bodyId}/></p></div>)}</div></Container></section>}
