import Image from "next/image";
import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/ui/Container";
import { PageHeroBackground } from "@/components/ui/PageHeroBackground";
import { PHOTOS } from "@/lib/data/photos";
import { PROJECTS } from "@/lib/data/projects";
export const metadata={title:"Projects",description:"Temporary project portfolio concepts across Supply, Trading & Construction."};
export default function ProjectsPage(){return <main><Navbar/><section className="pt-40 pb-20 bg-deep-blue relative overflow-hidden"><PageHeroBackground photo={PHOTOS.constructionAerial} priority/><Container className="relative"><span className="eyebrow text-electric">Projects</span><h1 className="text-white text-4xl md:text-h1 max-w-4xl mt-6">How our capabilities translate into project work.</h1><p className="text-white/70 text-body mt-6 max-w-2xl">These profiles describe the types of work GCN is positioned to support. They are capability-based examples, not claims of a specific client engagement unless separately verified.</p></Container></section><section className="py-20 bg-offwhite"><Container className="grid lg:grid-cols-2 gap-px bg-mist">{PROJECTS.map((p,i)=><Link key={p.slug} href={`/projects/${p.slug}`} className="bg-white group"><div className="relative h-72 overflow-hidden"><Image src={p.image.src} alt={p.image.alt} fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover transition-transform duration-700 group-hover:scale-105"/><span className="absolute top-5 left-5 bg-white px-3 py-2 text-[11px] uppercase tracking-widest text-deep-blue">{String(i+1).padStart(2,"0")} · {p.sector}</span></div><div className="p-8 md:p-10"><div className="flex flex-wrap gap-2">{p.tags.map(t=><span key={t} className="text-[11px] uppercase tracking-widest text-electric border border-pale-blue px-2 py-1">{t}</span>)}</div><h2 className="text-2xl text-navy mt-5">{p.title}</h2><p className="text-[15px] text-navy/60 mt-3">{p.challenge}</p><span className="inline-block mt-7 text-[13px] font-semibold text-electric">View profile →</span></div></Link>)}</Container></section><Footer/></main>}
