import Image from "next/image";
import Link from "next/link";
import {ArrowRight,CheckCircle2,FileCheck2,Handshake,Network,Plane,Search,ShieldCheck,Sparkles,TimerReset,Truck,Workflow} from "lucide-react";
import {Container} from "@/components/ui/Container";
import {T} from "@/components/i18n/T";

const capabilities=[
 {n:"01",title:"Aviation Supply",href:"/aviation-supply",image:"/assets/generated/industry-aviation.jpg",en:"Aircraft parts, consumables and procurement support with structured sourcing, documentation and supply coordination.",id:"Aircraft parts, consumables, dan dukungan procurement dengan sourcing, dokumentasi, serta koordinasi supply yang terstruktur."},
 {n:"02",title:"Procurement & Sourcing",href:"/procurement-sourcing",image:"/assets/generated/project-machinery-001.jpg",en:"Requirement review, supplier search, comparison, commercial evaluation and procurement coordination.",id:"Review kebutuhan, pencarian supplier, perbandingan, evaluasi komersial, dan koordinasi procurement."},
 {n:"03",title:"General Supply & Trading",href:"/general-supply-trading",image:"/assets/generated/project-building-material-001.jpg",en:"Structured B2B sourcing and supply aligned to specification, quantity, commercial terms and delivery requirements.",id:"Sourcing dan supply B2B terstruktur sesuai spesifikasi, kuantitas, syarat komersial, dan kebutuhan pengiriman."},
 {n:"04",title:"Industrial Supply",href:"/industrial-supply",image:"/assets/generated/industry-machinery.jpg",en:"Industrial materials, equipment and operational requirements sourced against defined customer specifications.",id:"Material, peralatan, dan kebutuhan operasional industri yang disourcing berdasarkan spesifikasi customer."},
 {n:"05",title:"Project-Based Supply",href:"/project-based-supply",image:"/assets/generated/industry-material.jpg",en:"Sourcing, costing, procurement, delivery and documentation coordinated around project requirements.",id:"Sourcing, costing, procurement, delivery, dan dokumentasi yang dikoordinasikan berdasarkan kebutuhan proyek."},
 {n:"06",title:"Construction",href:"/construction",image:"/assets/generated/industry-construction.jpg",en:"Construction execution and project coordination within verified business scope and applicable requirements.",id:"Pelaksanaan konstruksi dan koordinasi proyek sesuai ruang lingkup usaha terverifikasi serta persyaratan yang berlaku."},
];
const flow=[["Requirement / RFQ","Kebutuhan / RFQ"],["Sourcing","Sourcing"],["Costing & Evaluation","Costing & Evaluasi"],["Quotation","Quotation"],["Procurement / Execution","Procurement / Eksekusi"],["Delivery","Delivery"],["Documentation & Closing","Dokumentasi & Closing"]];
const sinergi=[
 ["S","Solutif","Understand the requirement and build a practical, valuable solution.","Memahami kebutuhan dan menghadirkan solusi yang tepat, realistis, dan bernilai."],
 ["I","Integritas","Act honestly, transparently and ethically in every relationship and transaction.","Jujur, transparan, etis, dan menjaga kepercayaan dalam setiap hubungan dan transaksi."],
 ["N","Nilai Berkelanjutan","Create healthy value for customers, GEGA and partners over the long term.","Menciptakan hasil yang sehat bagi pelanggan, GEGA, dan mitra untuk hubungan bisnis jangka panjang."],
 ["E","Eksekusi Unggul","Deliver with quality, accuracy, control and responsibility.","Menjalankan setiap pekerjaan dengan kualitas, ketepatan, kontrol, dan tanggung jawab."],
 ["R","Responsif","Understand quickly, provide clarity and resolve issues with discipline.","Cepat memahami kebutuhan, memberikan kepastian, dan menyelesaikan masalah."],
 ["G","Gesit","Move adaptively and quickly without sacrificing quality, compliance or control.","Adaptif dan cepat mengambil tindakan tanpa mengorbankan kualitas, compliance, atau kontrol."],
 ["I","Inovatif","Use technology, data and better ways of working to improve decisions and service.","Memanfaatkan teknologi, data, dan cara kerja baru untuk terus meningkatkan kualitas layanan dan pengambilan keputusan."],
];
const reasons=[
 {icon:Search,en:"Structured Sourcing",id:"Structured Sourcing",bodyEn:"Requirements are translated into source options, supplier comparisons and practical commercial choices.",bodyId:"Kebutuhan diterjemahkan menjadi opsi sumber, perbandingan supplier, dan pilihan komersial yang praktis."},
 {icon:TimerReset,en:"Responsive Coordination",id:"Koordinasi Responsif",bodyEn:"Clear ownership and timely follow-up across customer, supplier, logistics and project stakeholders.",bodyId:"PIC dan tindak lanjut yang jelas di antara customer, supplier, logistik, dan stakeholder proyek."},
 {icon:ShieldCheck,en:"Accountable Execution",id:"Eksekusi Akuntabel",bodyEn:"Key decisions, commitments and project documentation are handled with traceability in mind.",bodyId:"Keputusan, komitmen, dan dokumentasi proyek dikelola dengan mempertimbangkan traceability."},
 {icon:FileCheck2,en:"Documentation & Traceability",id:"Dokumentasi & Traceability",bodyEn:"Commercial and delivery records are treated as part of the job, not as an afterthought.",bodyId:"Dokumen komersial dan delivery diperlakukan sebagai bagian dari pekerjaan, bukan pelengkap belakangan."},
 {icon:Workflow,en:"Commercial Awareness",id:"Kesadaran Komersial",bodyEn:"Cost, lead time, risk, terms and execution implications are considered before commitment.",bodyId:"Biaya, lead time, risiko, termin, dan implikasi eksekusi dipertimbangkan sebelum komitmen."},
 {icon:Network,en:"Flexible Partner Network",id:"Jaringan Mitra Fleksibel",bodyEn:"GEGA can coordinate manufacturers, distributors, specialist suppliers, subcontractors and logistics partners as requirements demand.",bodyId:"GEGA dapat mengoordinasikan produsen, distributor, supplier spesialis, subcontractor, dan mitra logistik sesuai kebutuhan."},
];

export function HomeRedesign(){return <>
<section className="relative min-h-[760px] overflow-hidden bg-[#041827] pt-[72px] text-white md:pt-20">
 <Image src="/assets/generated/industry-aviation.jpg" alt="Lingkungan technical supply dan maintenance aviation" fill priority sizes="100vw" className="object-cover object-center opacity-[.34]"/>
 <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,24,39,.98)_0%,rgba(4,24,39,.88)_48%,rgba(4,24,39,.38)_100%)]"/>
 <div className="absolute inset-0 opacity-40 [background-image:radial-gradient(circle_at_72%_28%,rgba(0,169,244,.22),transparent_26%),linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] [background-size:auto,80px_80px,80px_80px]"/>
 <Container className="relative flex min-h-[688px] items-center py-16 md:py-24"><div className="max-w-[780px]"><div className="mb-6 flex flex-wrap items-center gap-3 text-[11px] font-semibold uppercase tracking-[.16em] text-cyan"><span className="h-px w-9 bg-cyan"/><T en="Aviation-led procurement, supply & project execution" id="Aviation-led procurement, supply & project execution"/></div><div className="text-[13px] font-semibold tracking-[.08em] text-white/70">Your Trusted Business Partner</div><h1 className="mt-5 max-w-4xl text-[3rem] font-semibold leading-[.98] tracking-[-.045em] text-white sm:text-[4rem] md:text-[5.4rem]"><T en="Connecting Needs. Creating Value." id="Menghubungkan Kebutuhan. Mewujudkan Nilai."/></h1><p className="mt-7 max-w-2xl text-[16px] leading-8 text-white/72 md:text-[18px]"><T en="GEGA helps businesses fulfill requirements through coordinated sourcing, procurement, supply and project execution — responsive, structured and accountable." id="GEGA membantu bisnis memenuhi kebutuhan melalui sourcing, procurement, supply, dan project execution yang terkoordinasi, responsif, terstruktur, dan dapat dipertanggungjawabkan."/></p><div className="mt-9 flex flex-wrap gap-3"><Link href="/rfq" className="inline-flex items-center gap-2 rounded-md bg-cyan px-6 py-4 text-sm font-bold text-[#041827] transition hover:bg-white"><T en="Submit RFQ" id="Ajukan RFQ"/><ArrowRight size={16}/></Link><Link href="/capabilities" className="inline-flex items-center gap-2 rounded-md border border-white/30 bg-white/[.05] px-6 py-4 text-sm font-semibold text-white backdrop-blur-sm transition hover:bg-white hover:text-[#041827]"><T en="Explore Capabilities" id="Lihat Kapabilitas"/></Link></div><div className="mt-12 grid max-w-2xl grid-cols-2 gap-px overflow-hidden rounded-xl border border-white/12 bg-white/10 sm:grid-cols-4"><div className="bg-[#061f33]/80 p-4"><Plane className="mb-3 text-cyan" size={19}/><div className="text-xs text-white/70">Aviation Supply</div></div><div className="bg-[#061f33]/80 p-4"><Search className="mb-3 text-cyan" size={19}/><div className="text-xs text-white/70">Sourcing</div></div><div className="bg-[#061f33]/80 p-4"><Handshake className="mb-3 text-cyan" size={19}/><div className="text-xs text-white/70">Partnership</div></div><div className="bg-[#061f33]/80 p-4"><Truck className="mb-3 text-cyan" size={19}/><div className="text-xs text-white/70">Execution</div></div></div></div></Container>
</section>
<section className="bg-white py-20 md:py-28"><Container><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><div className="section-kicker"><T en="GEGA at a glance" id="GEGA secara singkat"/></div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl"><T en="More than a supplier list." id="Lebih dari sekadar daftar supplier."/></h2></div><div><p className="max-w-3xl text-[17px] leading-8 text-navy/70"><T en="PT Gega Cahaya Nusantara is a project-based procurement, supply and trading company. We connect customer requirements with sourcing options, commercial evaluation, procurement coordination, delivery and accountable documentation." id="PT Gega Cahaya Nusantara adalah perusahaan procurement, supply, dan trading berbasis proyek. Kami menghubungkan kebutuhan customer dengan opsi sourcing, evaluasi komersial, koordinasi procurement, delivery, dan dokumentasi yang dapat dipertanggungjawabkan."/></p><div className="mt-7 flex flex-wrap gap-x-7 gap-y-3 text-sm font-medium text-corporate"><span>Procurement</span><span>Sourcing</span><span>Supply</span><span>Project Execution</span><span>Partnership</span></div></div></div></Container></section>
<section className="overflow-hidden bg-[#071f33] py-20 text-white md:py-28"><Container><div className="grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="relative min-h-[420px] overflow-hidden rounded-[26px]"><Image src="/assets/generated/project-aviation-001.jpg" alt="Visual representasi aviation procurement dan aircraft supply" fill sizes="(max-width:1024px) 100vw, 50vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#071f33]/80 via-transparent to-transparent"/><div className="absolute bottom-5 left-5 rounded-full border border-white/20 bg-[#071f33]/75 px-4 py-2 text-[11px] tracking-[.12em] text-white/80 backdrop-blur-md"><T en="REPRESENTATIONAL CAPABILITY VISUAL" id="VISUAL REPRESENTASI KAPABILITAS"/></div></div><div><div className="section-kicker text-cyan"><T en="Featured capability" id="Kapabilitas unggulan"/></div><h2 className="mt-4 text-4xl font-semibold tracking-[-.035em] text-white md:text-6xl">Aviation Supply</h2><p className="mt-4 text-lg font-medium text-cyan">Aircraft Parts, Consumables & Procurement Support</p><p className="mt-6 max-w-xl text-[16px] leading-8 text-white/68"><T en="GCN supports aviation-related RFQ sourcing and supply coordination subject to exact part requirements, supplier documentation, source availability and customer acceptance. The capability is designed around disciplined sourcing, documentation review, traceability awareness and commercial coordination — without implying manufacturer, MRO or authority approval status." id="GCN mendukung sourcing RFQ dan koordinasi supply aviation berdasarkan kebutuhan part yang tepat, dokumentasi supplier, ketersediaan sumber, dan acceptance customer. Kapabilitas ini dibangun dengan sourcing terstruktur, review dokumentasi, traceability awareness, dan koordinasi komersial—tanpa mengklaim status manufacturer, MRO, atau approval otoritas."/></p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Aircraft parts sourcing","Consumables & expendables","Documentation review","Supplier qualification awareness","Traceability control","Urgent / AOG sourcing support"].map(x=><div key={x} className="flex items-start gap-2 text-sm text-white/75"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-cyan"/><span>{x}</span></div>)}</div><Link href="/aviation-supply" className="mt-9 inline-flex items-center gap-2 text-sm font-semibold text-cyan hover:text-white"><T en="Explore Aviation Supply" id="Lihat Aviation Supply"/><ArrowRight size={16}/></Link></div></div></Container></section>
<section className="bg-[#f5f8fa] py-20 md:py-28"><Container><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><div className="section-kicker"><T en="Business capabilities" id="Kapabilitas bisnis"/></div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl"><T en="Built around the requirement, not a fixed catalogue." id="Dibangun berdasarkan kebutuhan, bukan katalog yang kaku."/></h2></div><Link href="/capabilities" className="text-sm font-semibold text-corporate hover:text-navy"><T en="View all capabilities →" id="Lihat semua kapabilitas →"/></Link></div><div className="mt-14 grid gap-5 lg:grid-cols-12">{capabilities.map((c,i)=><Link key={c.href} href={c.href} className={`group relative min-h-[330px] overflow-hidden rounded-2xl border border-navy/10 bg-white ${i===0?"lg:col-span-7 lg:min-h-[460px]":"lg:col-span-5"}`}><Image src={c.image} alt={`Visual representasi ${c.title}`} fill sizes={i===0?"(max-width:1024px) 100vw, 58vw":"(max-width:1024px) 100vw, 42vw"} className="object-cover transition duration-700 group-hover:scale-[1.03]"/><div className="absolute inset-0 bg-gradient-to-t from-[#041827]/95 via-[#041827]/40 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-white md:p-8"><div className="text-[11px] font-semibold tracking-[.15em] text-cyan">{c.n}</div><h3 className={`${i===0?"text-3xl md:text-4xl":"text-2xl"} mt-2 font-semibold text-white`}>{c.title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-white/70"><T en={c.en} id={c.id}/></p><span className="mt-5 inline-flex items-center gap-2 text-xs font-semibold text-cyan"><T en="Explore capability" id="Lihat kapabilitas"/><ArrowRight size={14}/></span></div></Link>)}</div></Container></section>
<section className="bg-white py-20 md:py-28"><Container><div className="max-w-2xl"><div className="section-kicker"><T en="How GEGA works" id="Cara GEGA bekerja"/></div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl"><T en="From requirement to documented closing." id="Dari kebutuhan hingga closing yang terdokumentasi."/></h2><p className="mt-5 text-[16px] leading-8 text-navy/65"><T en="A simplified commercial flow showing how a requirement moves through sourcing, evaluation, execution and delivery." id="Alur komersial sederhana yang menunjukkan bagaimana kebutuhan bergerak melalui sourcing, evaluasi, eksekusi, dan delivery."/></p></div><div className="mt-14 grid gap-3 md:grid-cols-7">{flow.map((x,i)=><div key={x[0]} className="relative rounded-xl border border-navy/10 bg-[#f7fafb] p-4 md:min-h-[148px]"><div className="text-[11px] font-bold text-cyan">0{i+1}</div><div className="mt-5 text-sm font-semibold leading-5 text-navy"><T en={x[0]} id={x[1]}/></div>{i<flow.length-1&&<ArrowRight size={15} className="absolute -right-[10px] top-1/2 z-10 hidden -translate-y-1/2 text-corporate md:block"/>}</div>)}</div></Container></section>
<section id="sinergi" className="relative overflow-hidden bg-[#061f33] py-20 text-white md:py-32"><div className="sinergi-orbit sinergi-orbit-one"/><div className="sinergi-orbit sinergi-orbit-two"/><Container className="relative"><div className="mx-auto max-w-3xl text-center"><div className="text-[11px] font-semibold uppercase tracking-[.18em] text-cyan"><T en="How we work" id="Cara Kami Bekerja"/></div><h2 className="mt-5 text-5xl font-semibold tracking-[.08em] text-white md:text-7xl">SINERGI</h2><p className="mx-auto mt-5 max-w-2xl text-[16px] leading-8 text-white/65"><T en="SINERGI is how GEGA creates value through trust, collaboration and execution." id="SINERGI adalah cara GEGA menciptakan nilai melalui kepercayaan, kolaborasi, dan eksekusi."/></p></div><div className="relative mx-auto mt-14 max-w-6xl"><div className="pointer-events-none absolute left-1/2 top-1/2 hidden h-px w-[70%] -translate-x-1/2 bg-gradient-to-r from-transparent via-cyan/45 to-transparent lg:block"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-7">{sinergi.map((v,i)=><div key={`${v[0]}-${i}`} className="group relative z-10 rounded-2xl border border-white/12 bg-white/[.055] p-5 backdrop-blur-sm transition duration-300 hover:-translate-y-1 hover:border-cyan/50 hover:bg-white/[.09]"><div className="flex h-11 w-11 items-center justify-center rounded-full border border-cyan/35 bg-cyan/10 text-xl font-bold text-cyan">{v[0]}</div><div className="mt-5 text-sm font-semibold text-white">{v[1]}</div><p className="mt-3 text-xs leading-5 text-white/58"><T en={v[2]} id={v[3]}/></p></div>)}</div></div><div className="mt-12 text-center text-sm font-semibold text-white/70"><T en="SINERGI is how GEGA works." id="SINERGI adalah cara GEGA bekerja."/></div></Container></section>
<section className="bg-white py-20 md:py-28"><Container><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div className="lg:sticky lg:top-28 lg:self-start"><div className="section-kicker"><T en="Why GEGA" id="Mengapa GEGA"/></div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl"><T en="Control where it matters. Flexibility where it helps." id="Kontrol pada hal yang penting. Fleksibel pada hal yang membantu."/></h2><p className="mt-5 text-[15px] leading-7 text-navy/65"><T en="The value is not a generic claim of best price or best quality. It is a disciplined way of coordinating requirements, sourcing, commercial decisions, documentation and execution." id="Nilainya bukan klaim generik harga terbaik atau kualitas terbaik. Nilainya ada pada cara terstruktur mengoordinasikan kebutuhan, sourcing, keputusan komersial, dokumentasi, dan eksekusi."/></p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-navy/10 bg-navy/10 sm:grid-cols-2">{reasons.map(r=><div key={r.en} className="bg-[#f8fafb] p-7 md:p-8"><r.icon size={23} className="text-corporate"/><h3 className="mt-5 text-lg font-semibold text-navy"><T en={r.en} id={r.id}/></h3><p className="mt-3 text-sm leading-6 text-navy/62"><T en={r.bodyEn} id={r.bodyId}/></p></div>)}</div></div></Container></section>
<section className="border-y border-navy/10 bg-[#f5f8fa] py-20 md:py-24"><Container><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div><div className="section-kicker"><T en="Transparent capability" id="Kapabilitas yang transparan"/></div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl"><T en="Credibility starts with claims that can be supported." id="Kredibilitas dimulai dari informasi yang dapat dipertanggungjawabkan."/></h2><p className="mt-5 max-w-xl text-[15px] leading-7 text-navy/65"><T en="GEGA presents its scope and operating approach based on capabilities that can be supported. Project references, customer identities and commercial details are shown only when verified and appropriate for public disclosure." id="GEGA menampilkan scope dan cara kerja berdasarkan kapabilitas yang dapat dipertanggungjawabkan. Referensi proyek, identitas customer, dan detail komersial hanya ditampilkan apabila telah terverifikasi dan layak dipublikasikan."/></p><Link href="/capabilities" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-corporate"><T en="See what we can support" id="Lihat kapabilitas GEGA"/><ArrowRight size={16}/></Link></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-[#061f33] p-7 text-white"><Sparkles className="text-cyan"/><h3 className="mt-5 text-xl font-semibold text-white"><T en="Modern Operations" id="Operasi Modern"/></h3><p className="mt-3 text-sm leading-6 text-white/60"><T en="Digital workflows, structured documentation, data and business intelligence support better operational control." id="Digital workflow, dokumentasi terstruktur, data, dan business intelligence mendukung kontrol operasional yang lebih baik."/></p></div><div className="rounded-2xl border border-navy/10 bg-white p-7"><FileCheck2 className="text-corporate"/><h3 className="mt-5 text-xl font-semibold text-navy">Documentation Mindset</h3><p className="mt-3 text-sm leading-6 text-navy/60"><T en="RFQ, supplier comparison, quotation, procurement, delivery and closing are treated as connected records." id="RFQ, supplier comparison, quotation, procurement, delivery, dan closing diperlakukan sebagai rangkaian record yang saling terhubung."/></p></div></div></div></Container></section>
<section className="bg-white py-20 md:py-28"><Container><div className="relative overflow-hidden rounded-[28px] bg-[#0a3650] px-7 py-10 text-white md:px-12 md:py-14"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full border border-cyan/20"/><div className="absolute -right-8 top-8 h-52 w-52 rounded-full border border-cyan/15"/><div className="relative grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><div className="text-[11px] font-semibold uppercase tracking-[.17em] text-cyan"><T en="Partnership ecosystem" id="Ekosistem kemitraan"/></div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-white md:text-5xl"><T en="Stronger requirements need the right network." id="Kebutuhan yang kompleks membutuhkan jaringan yang tepat."/></h2><p className="mt-5 max-w-2xl text-[15px] leading-7 text-white/65"><T en="GEGA builds relationships with suppliers, vendors, subcontractors, specialist providers, logistics partners and business partners to fulfill customer requirements more effectively and accountably." id="GEGA membangun hubungan dengan supplier, vendor, subcontractor, specialist provider, mitra logistik, dan business partner untuk memenuhi kebutuhan customer secara lebih efektif dan bertanggung jawab."/></p></div><div className="flex flex-wrap gap-3 lg:justify-end"><Link href="/partnership" className="rounded-md bg-white px-5 py-3.5 text-sm font-semibold text-[#061f33] hover:bg-cyan"><T en="Become a Vendor / Partner" id="Menjadi Vendor / Partner"/></Link></div></div></div></Container></section>
<section className="bg-[#041827] py-20 text-white md:py-28"><Container><div className="mx-auto max-w-4xl text-center"><div className="text-[11px] font-semibold uppercase tracking-[.17em] text-cyan"><T en="Start with the requirement" id="Mulai dari kebutuhan"/></div><h2 className="mt-5 text-4xl font-semibold tracking-[-.035em] text-white md:text-6xl"><T en="Have a requirement that needs to be sourced or executed?" id="Punya kebutuhan yang perlu segera dicari atau dikerjakan?"/></h2><p className="mx-auto mt-5 max-w-2xl text-[16px] leading-8 text-white/62"><T en="Send the requirement, specification or RFQ. GEGA will review the scope before the commercial sourcing process moves forward." id="Kirim kebutuhan, spesifikasi, atau RFQ. GEGA akan mereview scope sebelum proses sourcing komersial dilanjutkan."/></p><div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/rfq" className="inline-flex items-center gap-2 rounded-md bg-cyan px-6 py-4 text-sm font-bold text-[#041827] hover:bg-white"><T en="Submit RFQ" id="Ajukan RFQ"/><ArrowRight size={16}/></Link><Link href="/rfq?mode=consultation" className="rounded-md border border-white/25 px-6 py-4 text-sm font-semibold text-white hover:bg-white hover:text-[#041827]"><T en="Discuss a Requirement" id="Konsultasikan Kebutuhan"/></Link></div></div></Container></section>
</>}
