import type {Metadata} from "next";
import "./globals.css";
import ChatWidget from "@/components/ChatWidget";
import {LanguageProvider} from "@/lib/i18n/LanguageContext";
const SITE_URL="https://www.gcnusantara.com";
const INDEXABLE=process.env.NEXT_PUBLIC_SITE_INDEXABLE!=="false";
const SITE_NAME="GCN | PT Gega Cahaya Nusantara";
const SITE_TITLE="GCN | Procurement, Aviation Supply & Project Execution";
const SITE_DESCRIPTION="PT Gega Cahaya Nusantara (GEGA/GCN) — B2B procurement, sourcing, aviation supply, general supply, industrial supply and project execution in Indonesia.";
export const metadata:Metadata={metadataBase:new URL(SITE_URL),title:{default:SITE_TITLE,template:`%s | ${SITE_NAME}`},description:SITE_DESCRIPTION,applicationName:SITE_NAME,keywords:["aviation supply Indonesia","aircraft parts sourcing Indonesia","aviation procurement Indonesia","aircraft consumables supplier","procurement company Indonesia","sourcing company Indonesia","general supply Indonesia","industrial supply Indonesia","project based procurement","general contractor Indonesia","PT Gega Cahaya Nusantara","GEGA","GCN Indonesia"],alternates:{canonical:SITE_URL},openGraph:{type:"website",locale:"id_ID",alternateLocale:"en_US",url:SITE_URL,siteName:SITE_NAME,title:SITE_TITLE,description:SITE_DESCRIPTION,images:[{url:`${SITE_URL}/og-image.png`,width:1200,height:630,alt:SITE_TITLE}]},twitter:{card:"summary_large_image",title:SITE_TITLE,description:SITE_DESCRIPTION,images:[`${SITE_URL}/og-image.png`]},robots:{index:INDEXABLE,follow:INDEXABLE,googleBot:{index:INDEXABLE,follow:INDEXABLE}},manifest:"/site.webmanifest",icons:{icon:[{url:"/icon.png",sizes:"128x128",type:"image/png"},{url:"/favicon.ico",sizes:"any"}],shortcut:"/favicon.ico",apple:[{url:"/icon.png",sizes:"128x128",type:"image/png"}]}};
const organizationJsonLd={"@context":"https://schema.org","@type":"Organization","@id":`${SITE_URL}/#organization`,name:"PT Gega Cahaya Nusantara",legalName:"PT Gega Cahaya Nusantara",alternateName:["GEGA","GCN","Gega Cahaya Nusantara"],url:SITE_URL,logo:{"@type":"ImageObject",url:`${SITE_URL}/gcn-logo.svg`},image:`${SITE_URL}/og-image.png`,description:SITE_DESCRIPTION,email:"sales@gcnusantara.com",areaServed:"ID",address:{"@type":"PostalAddress",streetAddress:"Kawasan Pergudangan dan Industri PKT Bitung, Blok A6–A7",addressLocality:"Tangerang",addressRegion:"Banten",addressCountry:"ID"},knowsAbout:["Procurement","Sourcing","Aviation Supply","General Supply","Industrial Supply","Project-Based Supply","Construction"]};
const websiteJsonLd={"@context":"https://schema.org","@type":"WebSite","@id":`${SITE_URL}/#website`,url:SITE_URL,name:SITE_NAME,publisher:{"@id":`${SITE_URL}/#organization`}};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="id"><head><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(organizationJsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(websiteJsonLd)}}/></head><body><LanguageProvider>{children}<ChatWidget/></LanguageProvider></body></html>}
