import Image from "next/image";
import Link from "next/link";
import {ArrowRight,CheckCircle2,FileCheck2,Search,ShieldCheck,Workflow} from "lucide-react";
import {Navbar} from "@/components/layout/Navbar";
import {Footer} from "@/components/layout/Footer";
import {Container} from "@/components/ui/Container";
import type {CapabilityData} from "@/lib/data/capabilities-v2";

export function CapabilityPage({data,aviation=false}:{data:CapabilityData;aviation?:boolean}){return <main><Navbar/>
 <section className="relative min-h-[620px] overflow-hidden bg-[#041827] pt-[72px] text-white md:pt-20"><Image src={data.image} alt={`Representational visual for ${data.title}`} fill priority sizes="100vw" className="object-cover opacity-[.34]"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,24,39,.98),rgba(4,24,39,.82)_55%,rgba(4,24,39,.38))]"/><Container className="relative flex min-h-[548px] items-end pb-16 pt-24 md:pb-20"><div className="max-w-3xl"><div className="text-[11px] font-semibold uppercase tracking-[.17em] text-cyan">{data.eyebrow}</div><h1 className="mt-5 text-5xl font-semibold tracking-[-.045em] text-white md:text-7xl">{data.title}</h1><div className="mt-4 text-lg font-medium text-cyan md:text-xl">{data.descriptor}</div><p className="mt-6 max-w-2xl text-[16px] leading-8 text-white/70">{data.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={aviation?"/rfq?businessLine=Aviation%20Supply":"/rfq"} className="inline-flex items-center gap-2 rounded-md bg-cyan px-6 py-4 text-sm font-bold text-[#041827] hover:bg-white">{aviation?"Submit Aviation RFQ":"Ajukan RFQ"}<ArrowRight size={16}/></Link><a href="#scope" className="rounded-md border border-white/25 px-6 py-4 text-sm font-semibold text-white hover:bg-white hover:text-[#041827]">Explore Capability</a></div></div></Container></section>

 <section className="bg-white py-20 md:py-24"><Container><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><div className="section-kicker">Problems We Help Solve</div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-4xl">Requirement first. Source second.</h2></div><div className="grid gap-px overflow-hidden rounded-2xl border border-navy/10 bg-navy/10 sm:grid-cols-2">{data.problems.map(x=><div key={x} className="bg-[#f8fafb] p-6"><CheckCircle2 size={20} className="text-corporate"/><p className="mt-4 text-sm leading-6 text-navy/70">{x}</p></div>)}</div></div></Container></section>

 <section id="scope" className="bg-[#f4f8fa] py-20 md:py-24"><Container><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><div className="section-kicker">Scope</div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl">What we support</h2><p className="mt-5 text-sm leading-7 text-navy/60">Capability is presented based on documented operating scope. Specific availability, source, lead time and acceptance remain requirement-dependent.</p></div><div className="grid gap-3 sm:grid-cols-2">{data.scope.map(x=><div key={x} className="rounded-xl border border-navy/10 bg-white p-5"><div className="flex gap-3"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-cyan"/><span className="text-sm font-medium leading-6 text-navy">{x}</span></div></div>)}</div></div></Container></section>

 <section className="bg-white py-20 md:py-24"><Container><div className="max-w-2xl"><div className="section-kicker">How We Work</div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy md:text-5xl">A controlled path through the requirement</h2></div><div className="mt-12 grid gap-3 md:grid-cols-3 lg:grid-cols-4">{data.workflow.map((x,i)=><div key={x} className="relative rounded-xl border border-navy/10 bg-white p-5"><div className="text-[11px] font-bold text-cyan">{String(i+1).padStart(2,"0")}</div><div className="mt-4 text-sm font-semibold text-navy">{x}</div>{i<data.workflow.length-1&&<ArrowRight size={14} className="absolute -right-[9px] top-1/2 z-10 hidden -translate-y-1/2 text-corporate lg:block"/>}</div>)}</div></Container></section>

 <section className="bg-[#061f33] py-20 text-white md:py-24"><Container><div className="grid gap-12 lg:grid-cols-2"><div><div className="flex h-11 w-11 items-center justify-center rounded-full bg-cyan/10 text-cyan"><ShieldCheck size={22}/></div><h2 className="mt-5 text-3xl font-semibold tracking-[-.03em] text-white md:text-4xl">Documentation & Control</h2><div className="mt-7 grid gap-3">{data.controls.map(x=><div key={x} className="flex gap-3 border-b border-white/10 pb-3 text-sm leading-6 text-white/70"><FileCheck2 size={17} className="mt-1 shrink-0 text-cyan"/><span>{x}</span></div>)}</div></div><div><div className="flex h-11 w-11 items-center justify-center rounded-full bg-cyan/10 text-cyan"><Search size={22}/></div><h2 className="mt-5 text-3xl font-semibold tracking-[-.03em] text-white md:text-4xl">Why Work With GCN</h2><div className="mt-7 grid gap-3">{data.why.map(x=><div key={x} className="flex gap-3 border-b border-white/10 pb-3 text-sm leading-6 text-white/70"><Workflow size={17} className="mt-1 shrink-0 text-cyan"/><span>{x}</span></div>)}</div></div></div>{data.disclaimer&&<div className="mt-12 rounded-xl border border-cyan/20 bg-cyan/[.06] p-5 text-xs leading-6 text-white/60"><strong className="text-white/80">Capability statement:</strong> {data.disclaimer}</div>}</Container></section>

 <section className="bg-white py-20 md:py-24"><Container><div className="flex flex-col items-start justify-between gap-7 rounded-[24px] bg-[#edf5f7] p-8 md:flex-row md:items-center md:p-12"><div><div className="text-[11px] font-semibold uppercase tracking-[.16em] text-corporate">Commercial Enquiry</div><h2 className="mt-3 text-3xl font-semibold tracking-[-.03em] text-navy">{aviation?"Have an aircraft parts requirement?":"Punya kebutuhan yang perlu disourcing?"}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-navy/60">Send the requirement, specification and target date so the team can review the sourcing path and commercial next step.</p></div><Link href={aviation?"/rfq?businessLine=Aviation%20Supply":"/rfq"} className="inline-flex shrink-0 items-center gap-2 rounded-md bg-[#061f33] px-6 py-4 text-sm font-semibold text-white hover:bg-corporate">{aviation?"Submit Aviation RFQ":"Ajukan RFQ"}<ArrowRight size={16}/></Link></div></Container></section>
 <Footer/></main>}
