import type {Metadata} from "next";
import Image from "next/image";
import {FileCheck2,ShieldCheck,Workflow} from "lucide-react";
import {Navbar} from "@/components/layout/Navbar";
import {Footer} from "@/components/layout/Footer";
import {Container} from "@/components/ui/Container";
import {RFQForm} from "@/components/forms/RFQForm";
export const metadata:Metadata={title:"Ajukan RFQ | Procurement & Aviation Supply",description:"Ajukan kebutuhan procurement, sourcing, aviation supply, general supply, industrial supply, project-based supply atau construction kepada PT Gega Cahaya Nusantara.",alternates:{canonical:"https://www.gcnusantara.com/rfq"}};
export default function RFQPage(){return <main><Navbar/><section className="relative overflow-hidden bg-[#041827] pt-[72px] text-white md:pt-20"><Image src="/assets/generated/industry-aviation.jpg" alt="Representational technical supply and procurement environment" fill priority sizes="100vw" className="object-cover opacity-[.2]"/><div className="absolute inset-0 bg-gradient-to-r from-[#041827] via-[#041827]/96 to-[#041827]/70"/><Container className="relative py-20 md:py-24"><div className="max-w-3xl"><div className="text-[11px] font-semibold uppercase tracking-[.17em] text-cyan">Commercial RFQ</div><h1 className="mt-5 text-5xl font-semibold tracking-[-.045em] text-white md:text-7xl">Sampaikan kebutuhan Anda.</h1><p className="mt-6 max-w-2xl text-[17px] leading-8 text-white/68">Kirim requirement, spesifikasi, target waktu, dan dokumen pendukung. Tim GEGA akan melakukan review awal sebelum sourcing dan proses komersial dilanjutkan.</p></div></Container></section><section className="bg-white py-20 md:py-24"><Container className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><aside className="lg:sticky lg:top-28 lg:self-start"><div className="section-kicker">Before You Submit</div><h2 className="mt-4 text-3xl font-semibold tracking-[-.03em] text-navy">Requirement yang jelas mempercepat sourcing.</h2><div className="mt-7 grid gap-5"><div className="flex gap-3"><Workflow size={20} className="mt-1 shrink-0 text-corporate"/><div><div className="text-sm font-semibold text-navy">Scope & Specification</div><p className="mt-1 text-xs leading-5 text-navy/55">Jelaskan item/service, quantity, spesifikasi dan target delivery.</p></div></div><div className="flex gap-3"><FileCheck2 size={20} className="mt-1 shrink-0 text-corporate"/><div><div className="text-sm font-semibold text-navy">Supporting Documents</div><p className="mt-1 text-xs leading-5 text-navy/55">RFQ, BOQ, drawing, atau specification dapat dilampirkan bila tersedia.</p></div></div><div className="flex gap-3"><ShieldCheck size={20} className="mt-1 shrink-0 text-corporate"/><div><div className="text-sm font-semibold text-navy">Controlled Intake</div><p className="mt-1 text-xs leading-5 text-navy/55">Submission divalidasi server-side dan diteruskan melalui jalur commercial intake GCN.</p></div></div></div></aside><div className="rounded-2xl border border-navy/10 bg-[#fbfcfd] p-6 md:p-9"><RFQForm/></div></Container></section><Footer/></main>}
