import {NextRequest,NextResponse} from "next/server";
import {Resend} from "resend";
import {SALES_TO,SALES_CC} from "@/lib/mail-recipients";
const REQUIRED_FIELDS=["companyName","contactPerson","email","phone","industry","requirementCategory","productOrService","specification","quantity","requiredDeliveryDate","deliveryLocation"] as const;
const MAX_ATTACHMENT_BYTES=8*1024*1024;
const ALLOWED_EXTENSIONS=new Set(["pdf","xls","xlsx","doc","docx"]);
const ALLOWED_MIME_TYPES=new Set(["application/pdf","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/octet-stream"]);
const ERP_API_URL=(process.env.GCN_ERP_API_URL||"https://api-mis.gcnusantara.com").replace(/\/$/,"");
function clean(value:FormDataEntryValue|null,max=4000){return String(value??"").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,"").trim().slice(0,max)}
async function pushLeadToErp(payload:Record<string,string>){const token=process.env.GCN_WEBSITE_LEAD_TOKEN;if(!token){console.warn("GCN_WEBSITE_LEAD_TOKEN is not set; ERP lead sync skipped while email fallback remains active.");return{ok:false,skipped:true}}try{const res=await fetch(`${ERP_API_URL}/api/public/website-lead`,{method:"POST",headers:{"Content-Type":"application/json","x-gcn-website-token":token},body:JSON.stringify(payload),signal:AbortSignal.timeout(12000),cache:"no-store"});const data=await res.json().catch(()=>null);if(!res.ok){console.error("ERP lead sync rejected:",{status:res.status,data});return{ok:false,skipped:false}}return{ok:true,skipped:false,leadId:data?.lead_id,duplicate:!!data?.duplicate}}catch(error){console.error("ERP lead sync failed:",error);return{ok:false,skipped:false}}}
export async function POST(req:NextRequest){const formData=await req.formData().catch(()=>null);if(!formData)return NextResponse.json({error:"Invalid form data"},{status:400});const field=(key:string,max=4000)=>clean(formData.get(key),max);if(field("hp_ref_note",200)!=="")return NextResponse.json({ok:true});if(field("consent",20)!=="on")return NextResponse.json({error:"Consent required"},{status:400});const data:Record<string,string>={};const missing:string[]=[];for(const key of REQUIRED_FIELDS){const max=key==="specification"?6000:500;const value=field(key,max);if(!value)missing.push(key);data[key]=value}if(missing.length)return NextResponse.json({error:"Missing required fields",fields:missing},{status:400});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)||data.email.length>254)return NextResponse.json({error:"Invalid email"},{status:400});
 const optional={position:field("position",200),budgetRange:field("budgetRange",300),paymentTerms:field("paymentTerms",500),additionalInformation:field("additionalInformation",6000),partNumber:field("partNumber",300),conditionRequirement:field("conditionRequirement",500),certificationRequirement:field("certificationRequirement",1000),aircraftApplication:field("aircraftApplication",500),sourcePage:field("sourcePage",500)};
 const file=formData.get("attachment");const attachments:{filename:string;content:Buffer}[]=[];if(file instanceof File&&file.size>0){if(file.size>MAX_ATTACHMENT_BYTES)return NextResponse.json({error:"Attachment too large (max 8MB)"},{status:400});const ext=file.name.toLowerCase().split(".").pop()||"";if(!ALLOWED_EXTENSIONS.has(ext)||!ALLOWED_MIME_TYPES.has(file.type||"application/octet-stream"))return NextResponse.json({error:"Unsupported attachment type"},{status:400});const safeName=file.name.replace(/[^a-zA-Z0-9._ -]/g,"_").slice(0,180);attachments.push({filename:safeName,content:Buffer.from(await file.arrayBuffer())})}
 const aviationLines=data.industry==="Aviation Supply"?["AVIATION DETAILS",`Part Number: ${optional.partNumber||"Not provided"}`,`Condition Requirement: ${optional.conditionRequirement||"Not provided"}`,`Certification / Documentation Requirement: ${optional.certificationRequirement||"Not provided"}`,`Aircraft / Application: ${optional.aircraftApplication||"Not provided"}`]:[];
 const mergedAdditionalInformation=[optional.additionalInformation,...aviationLines].filter(Boolean).join("\n").slice(0,7000);
 const submittedAt=new Date().toISOString();const leadPayload={...data,position:optional.position,budgetRange:optional.budgetRange,paymentTerms:optional.paymentTerms,additionalInformation:mergedAdditionalInformation,sourcePage:optional.sourcePage,submittedAt,source:"Website RFQ",website:"gcnusantara.com"};const erpSync=await pushLeadToErp(leadPayload);
 const bodyLines=["NEW WEBSITE RFQ — SALES FOLLOW-UP REQUIRED","","CUSTOMER",`Company: ${data.companyName}`,`PIC: ${data.contactPerson}`,`Position: ${optional.position||"Not provided"}`,`Email: ${data.email}`,`Phone / Contact: ${data.phone}`,"","REQUIREMENT",`Business Line: ${data.industry}`,`Requirement Type: ${data.requirementCategory}`,`Item / Service: ${data.productOrService}`,`Specification / Scope: ${data.specification}`,`Quantity: ${data.quantity}`,`Required Date: ${data.requiredDeliveryDate}`,`Delivery / Project Location: ${data.deliveryLocation}`,`Budget Range: ${optional.budgetRange||"Not provided"}`,`Preferred Payment Terms: ${optional.paymentTerms||"Not provided"}`,`Additional Notes: ${mergedAdditionalInformation||"-"}`,"",`Submitted At: ${submittedAt}`,`Source Page: ${optional.sourcePage||"/rfq"}`,`ERP Lead Sync: ${erpSync.ok?`SYNCED${erpSync.leadId?` (${erpSync.leadId})`:""}`:erpSync.skipped?"PENDING ENV CONFIG":"FAILED - CHECK LOGS"}`,"Recommended next action: qualify requirement → sourcing/costing → quotation.","Source: gcnusantara.com RFQ"];
 const apiKey=process.env.RESEND_API_KEY;if(!apiKey){if(erpSync.ok)return NextResponse.json({ok:true,source:"website-rfq",erpSync:true,emailSent:false,submittedAt});return NextResponse.json({error:"Lead delivery services not configured"},{status:500})}
 try{const result=await new Resend(apiKey).emails.send({from:"GCN Website <no-reply@gcnusantara.com>",to:SALES_TO,cc:SALES_CC,replyTo:data.email,subject:`[NEW RFQ][${data.industry}] ${data.companyName} — ${data.productOrService}`,text:bodyLines.join("\n"),attachments:attachments.length?attachments:undefined});if(result.error){console.error("Resend rejected RFQ:",result.error);if(erpSync.ok)return NextResponse.json({ok:true,source:"website-rfq",erpSync:true,emailSent:false,submittedAt});return NextResponse.json({error:"Failed to deliver RFQ"},{status:502})}return NextResponse.json({ok:true,source:"website-rfq",erpSync:erpSync.ok,erpLeadId:erpSync.leadId||null,duplicate:erpSync.duplicate||false,emailSent:true,submittedAt})}catch(error){console.error("Failed to send RFQ email:",error);if(erpSync.ok)return NextResponse.json({ok:true,source:"website-rfq",erpSync:true,emailSent:false,submittedAt});return NextResponse.json({error:"Failed to deliver RFQ"},{status:500})}}
