import type {Metadata} from "next";
import Image from "next/image";
import Link from "next/link";
import {ArrowRight} from "lucide-react";
import {Navbar} from "@/components/layout/Navbar";
import {Footer} from "@/components/layout/Footer";
import {Container} from "@/components/ui/Container";
import {CAPABILITY_DATA,CapabilityKey} from "@/lib/data/capabilities-v2";
export const metadata:Metadata={title:"Kapabilitas | Aviation, Procurement, Supply & Construction",description:"Kapabilitas GEGA untuk Aviation Supply, Procurement & Sourcing, General Supply & Trading, Industrial Supply, Project-Based Supply dan Construction.",alternates:{canonical:"https://gcnusantara.com/capabilities"}};
const ORDER:CapabilityKey[]=["aviation","procurement","general-supply","industrial","project-supply","construction"];
export default function Page(){return <main><Navbar/><section className="bg-[#041827] pt-[72px] text-white md:pt-20"><Container className="py-20 md:py-28"><div className="max-w-4xl"><div className="text-[11px] font-semibold uppercase tracking-[.17em] text-cyan">Capabilities</div><h1 className="mt-5 text-5xl font-semibold tracking-[-.045em] text-white md:text-7xl">Kapabilitas yang mengikuti kebutuhan bisnis.</h1><p className="mt-6 max-w-2xl text-[17px] leading-8 text-white/68">GEGA menggabungkan sourcing, procurement, supply, koordinasi komersial, project execution, dan dokumentasi sesuai kebutuhan setiap engagement.</p></div></Container></section><section className="bg-[#f4f8fa] py-20 md:py-28"><Container><div className="grid gap-5 lg:grid-cols-2">{ORDER.map((k,i)=>{const c=CAPABILITY_DATA[k];return <Link key={c.slug} href={`/${c.slug}`} className={`group relative min-h-[380px] overflow-hidden rounded-2xl ${i===0?"lg:col-span-2 lg:min-h-[520px]":""}`}><Image src={c.image} alt={`Representational visual for ${c.title}`} fill sizes={i===0?"100vw":"(max-width:1024px) 100vw, 50vw"} className="object-cover transition duration-700 group-hover:scale-[1.03]"/><div className="absolute inset-0 bg-gradient-to-t from-[#041827]/95 via-[#041827]/45 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-white md:p-9"><div className="text-[11px] font-bold tracking-[.15em] text-cyan">0{i+1}</div><h2 className={`${i===0?"text-4xl md:text-5xl":"text-3xl"} mt-3 font-semibold text-white`}>{c.title}</h2><div className="mt-2 text-sm font-medium text-cyan">{c.descriptor}</div><p className="mt-4 max-w-2xl text-sm leading-6 text-white/67">{c.intro}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-cyan">Explore capability <ArrowRight size={15}/></span></div></Link>})}</div></Container></section><Footer/></main>}
