"use client";
import {FormEvent,useEffect,useState} from "react";
import {Button} from "@/components/ui/Button";
import {TextField,SelectField,TextareaField,ConsentCheckbox,HoneypotField} from "@/components/forms/Fields";
import {useLanguage} from "@/lib/i18n/LanguageContext";
type Status="idle"|"submitting"|"success"|"error";
const BUSINESS_LINES=["Aviation Supply","Procurement & Sourcing","General Supply & Trading","Industrial Supply","Project-Based Supply","Construction"];
const REQUIREMENT_TYPES=["Product / Material","Sourcing / Procurement Support","Project-Based Requirement","Construction / Site Work","Other Business Requirement"];
const LINE_ID:Record<string,string>={"Aviation Supply":"Aviation Supply","Procurement & Sourcing":"Procurement & Sourcing","General Supply & Trading":"General Supply & Trading","Industrial Supply":"Industrial Supply","Project-Based Supply":"Project-Based Supply","Construction":"Konstruksi"};
const TYPE_ID:Record<string,string>={"Product / Material":"Produk / Material","Sourcing / Procurement Support":"Dukungan Sourcing / Procurement","Project-Based Requirement":"Kebutuhan Berbasis Proyek","Construction / Site Work":"Konstruksi / Pekerjaan Lapangan","Other Business Requirement":"Kebutuhan Bisnis Lain"};
export function RFQForm(){const[status,setStatus]=useState<Status>("idle");const[businessLine,setBusinessLine]=useState("");const{lang}=useLanguage();useEffect(()=>{const q=new URLSearchParams(window.location.search);const requested=q.get("businessLine");if(requested&&BUSINESS_LINES.includes(requested))setBusinessLine(requested)},[]);
 async function handleSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("submitting");const form=e.currentTarget;const formData=new FormData(form);formData.set("sourcePage",window.location.pathname+window.location.search);try{const res=await fetch("/api/rfq",{method:"POST",body:formData});if(!res.ok)throw new Error();setStatus("success");form.reset();setBusinessLine("");}catch{setStatus("error");}}
 if(status==="success")return <div className="rounded-2xl border border-cyan/20 bg-[#f2f8fa] p-10 text-center flex flex-col items-center gap-3"><h3 className="text-2xl font-semibold text-navy">{lang==="id"?"RFQ berhasil dikirim.":"RFQ submitted."}</h3><p className="text-body text-navy/70 max-w-md">{lang==="id"?"Kebutuhan Anda sudah masuk untuk review awal dan tindak lanjut komersial. Pengiriman RFQ tidak otomatis berarti quotation atau acceptance.":"Your requirement has been submitted for initial review and commercial follow-up. Submission does not automatically constitute a quotation or acceptance."}</p><Button variant="ghost" onClick={()=>setStatus("idle")} className="mt-2 normal-case tracking-normal">{lang==="id"?"Ajukan RFQ lain":"Submit another RFQ"}</Button></div>;
 return <form onSubmit={handleSubmit} className="flex flex-col gap-6"><HoneypotField/><div className="rounded-xl border border-cyan/20 bg-cyan/[.05] p-4 text-sm leading-6 text-navy/70">{lang==="id"?"Semakin lengkap spesifikasi, quantity, lokasi, target waktu, dan dokumen pendukung, semakin efektif proses review dan sourcing awal.":"Complete specifications, quantity, location, target date and supporting documents help make the initial review and sourcing process more effective."}</div><div className="grid md:grid-cols-2 gap-6"><TextField label="Company Name" labelId="Nama Perusahaan" name="companyName" required/><TextField label="Contact Person" labelId="Nama PIC" name="contactPerson" required/></div><div className="grid md:grid-cols-2 gap-6"><TextField label="Position" labelId="Jabatan" name="position"/><TextField label="Phone / Contact" labelId="Telepon / Kontak" name="phone" type="tel" required/></div><TextField label="Email" labelId="Email" name="email" type="email" required/><div className="grid md:grid-cols-2 gap-6"><SelectField label="Business Line" labelId="Business Line" name="industry" options={BUSINESS_LINES} optionLabelsId={LINE_ID} value={businessLine} onChange={e=>setBusinessLine(e.target.value)} required/><SelectField label="Requirement Type" labelId="Jenis Kebutuhan" name="requirementCategory" options={REQUIREMENT_TYPES} optionLabelsId={TYPE_ID} required/></div><TextField label="Item / Service Requirement" labelId="Item / Layanan yang Dibutuhkan" name="productOrService" required/><TextareaField label="Specification / Scope" labelId="Spesifikasi / Scope" name="specification" required/><div className="grid md:grid-cols-2 gap-6"><TextField label="Quantity" labelId="Kuantitas" name="quantity" required/><TextField label="Target Delivery / Completion Date" labelId="Target Delivery / Penyelesaian" name="requiredDeliveryDate" type="date" required/></div><TextField label="Delivery / Project Location" labelId="Lokasi Pengiriman / Proyek" name="deliveryLocation" required/>
 {businessLine==="Aviation Supply"&&<div className="rounded-2xl border border-cyan/20 bg-[#f4f9fb] p-5 md:p-6"><div className="mb-5"><div className="text-[11px] font-semibold uppercase tracking-[.15em] text-corporate">Aviation RFQ Details</div><p className="mt-2 text-xs leading-5 text-navy/55">Isi hanya data yang relevan dengan requirement. Exact part number, condition, dan required documentation membantu mengurangi ambiguity saat sourcing.</p></div><div className="grid gap-6 md:grid-cols-2"><TextField label="Part Number" labelId="Part Number" name="partNumber"/><TextField label="Condition Requirement" labelId="Condition Requirement" name="conditionRequirement" placeholder="e.g. NEW / NE / OH / SV, if applicable"/><TextField label="Certification / Documentation Requirement" labelId="Kebutuhan Sertifikat / Dokumentasi" name="certificationRequirement" placeholder="e.g. customer-required documentation"/><TextField label="Aircraft / Application (if relevant)" labelId="Aircraft / Application (jika relevan)" name="aircraftApplication"/></div></div>}
 <div className="grid md:grid-cols-2 gap-6"><TextField label="Budget Range" labelId="Kisaran Anggaran" name="budgetRange" placeholder={lang==="id"?"Opsional":"Optional"}/><TextField label="Preferred Payment Terms" labelId="Preferensi Termin Pembayaran" name="paymentTerms" placeholder={lang==="id"?"Opsional":"Optional"}/></div><div><label className="text-[13px] font-medium text-navy/70 mb-2 block">{lang==="id"?"Lampiran RFQ / BOQ / Specification / Drawing":"RFQ / BOQ / Specification / Drawing Attachment"}</label><input type="file" name="attachment" accept=".pdf,.xls,.xlsx,.doc,.docx" className="w-full rounded-md border border-mist bg-white px-4 py-3 text-[14px] text-navy/70 file:mr-4 file:rounded file:border-0 file:bg-[#061f33] file:px-4 file:py-2 file:text-[12px] file:text-white"/><p className="mt-2 text-xs text-navy/45">PDF, XLS/XLSX, DOC/DOCX. Maksimum 8 MB.</p></div><TextareaField label="Additional Notes" labelId="Catatan Tambahan" name="additionalInformation"/><ConsentCheckbox name="consent"/>{status==="error"&&<p className="text-[14px] text-red-600">{lang==="id"?"RFQ belum berhasil terkirim. Silakan periksa data atau coba kembali.":"The RFQ could not be submitted. Please review the data or try again."}</p>}<Button type="submit" disabled={status==="submitting"} className="w-fit">{status==="submitting"?(lang==="id"?"Mengirim...":"Submitting..."):(lang==="id"?"Kirim RFQ untuk Direview":"Submit RFQ for Review")}</Button></form>}
